add_newline = true
format="$directory$git_branch\n$character"
scan_timeout = 200

# Prompt symbols 
[character]
success_symbol = "[🞈](#a6e3a1 bold)"
error_symbol   = "[🞈](#f38ba8)"
vicmd_symbol   = "[🞈](#f9e2af)"

[directory]
format = "[]($style)[(bg:#f5c2e7 fg:#eba0ac)$path](bg:#f5c2e7 fg:#a84c8d)[ ]($style)"
style = "fg:#f5c2e7 fg:#f5c2e7"

#[git_branch]
#style = "bg:#f5c2e7 fg:#f5c2e7"
#format = "[]($style)[[ ](bg:#f5c2e7 fg:#eba0ac)$branch](bg:#f5c2e7 fg:#a84c8d)[ ]($style)"
