#!/usr/bin/bash

# Variables
config=/home/lumi/.config/hypr/
scripts=$config/scripts/

# Notifications
dunst &

# Waybar
$scripts/launch_waybar &
$scripts/tools/dynamic &

# Wallpaper
$scripts/wall $config/wallpapers/train.jpg &

# Effects
$scripts/rgb &

# Misc
udiskie --tray &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
wl-clipboard-history -t &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
