#!/usr/bin/bash

# Variables
config=/home/lumi/.config/hypr/

# Notifications
dunst &

# Waybar
waybar &

# Wallpaper
hyprpaper &

# Misc
udiskie --tray &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
wl-clipboard-history -t &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
